name:
  .trash: ï‡¸
  .cargo: î¨
  .emacs.d: î¹
  a.out: ï’‰
extension:
  go: î˜§
  hs: î·
  rs: ğŸ¦€
  py: îœ¼
  js: î
  java: î‰–
  md: îœ¾
  apk:îœ
  ipa:îœ‘
  dmg:îœ‘
  pkg:îœ‘

filetype:
  dir: ğŸ“‚
  file: ğŸ“„
  pipe: ğŸ“©
  socket: ó°†¨
  executable: ï’‰
  symlink-dir: ï’‚
  symlink-file: ï’
  device-char: î˜
  device-block: ó°œ«
  special: ï‹œ
